name: Auto-merge contributions from Sadnik13

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'Sadnik13' && github.event.pull_request.head.repo.full_name == 'Sadnik13/aurora-switch'
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Wait for checks (if any)
        run: sleep 10
      
      - name: Approve PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: '✅ Automatically approved contribution from Sadnik13'
            });
      
      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --squash \
            --auto \
            --delete-branch
      
      - name: Add comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '🤖 Automatically merged by GitHub Actions'
            });
