name: Auto-merge contributions from Sadnik13

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'Sadnik13' && github.event.pull_request.head.repo.full_name == 'Sadnik13/aurora-switch'
    
    permissions:
      contents: write
      pull-requests: write
      issues: write  # Для добавления комментариев
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Wait for other checks
        run: sleep 15
      
      - name: Approve PR
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve --body "✅ Automatically approved contribution from Sadnik13"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Enable auto-merge
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
