name: Manual contribution creator

on:
  workflow_dispatch:
    inputs:
      parent_repo:
        description: 'Parent repository (owner/repo)'
        required: true
        default: 'huynhhain/aurora-switch'
        type: string
      commit_type:
        description: 'Commit type'
        required: true
        default: 'docs'
        type: choice
        options:
          - docs
          - refactor
          - style
          - perf
          - chore
          - fix
          - feat
      target_file:
        description: 'File to modify'
        required: true
        default: 'Main.kt'
        type: string
      custom_message:
        description: 'Custom message (optional)'
        required: false
        type: string

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Display target info
        run: |
          echo "🎯 Target repository: ${{ inputs.parent_repo }}"
          echo "📝 Commit type: ${{ inputs.commit_type }}"
          echo "📄 File: ${{ inputs.target_file }}"
      
      - name: Create new branch
        id: branch
        run: |
          TIMESTAMP=$(date +%s)
          BRANCH_NAME="auto/${{ inputs.commit_type }}-${TIMESTAMP}"
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          git checkout -b ${BRANCH_NAME}
          echo "✅ Branch created: ${BRANCH_NAME}"
      
      - name: Check if file exists and create if needed
        run: |
          TARGET_FILE="${{ inputs.target_file }}"
          
          # Check if file exists
          if [ ! -f "$TARGET_FILE" ]; then
            echo "⚠️ File $TARGET_FILE does not exist, creating..."
            # Create directories if needed
            mkdir -p "$(dirname "$TARGET_FILE")"
            # Create file with basic content
            echo "// Auto-generated file" > "$TARGET_FILE"
            echo "✅ File created: $TARGET_FILE"
          else
            echo "✅ File exists: $TARGET_FILE"
          fi
      
      - name: Generate changes
        run: |
          TARGET_FILE="${{ inputs.target_file }}"
          COMMIT_MSG="${{ inputs.custom_message }}"
          
          # Generate unique ID to guarantee changes
          UNIQUE_ID=$(date +%s%N | md5sum | head -c 8)
          
          # If no custom message, generate automatic one
          if [ -z "$COMMIT_MSG" ]; then
            case "${{ inputs.commit_type }}" in
              "
